settings.settings:
  path: '/admin/settings'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Settings'
  requirements:
    _permission: 'access settings'
  options:
    _admin_route: TRUE
