toolbar:
  version: 'VERSION'
  css:
    theme:
      css/toolbar.icons.theme.css: {}
  dependencies:
    - 'toolbar/toolbar'

gin:
  version: 'VERSION'
  css:
    theme:
      css/gin.icons.theme.css: {}
  dependencies:
    - 'toolbar/toolbar'
