name: Settings - Communication
type: module
description: Provide a collection of communication settings and a way to manage them.
core_version_requirement: ^8.7.7 || ^9
package: Settings
dependencies:
  settings:settings
