name: Settings - Communication
type: module
description: Provide a collection of communication settings and a way to manage them.
core_version_requirement: ^9.1
package: Settings
dependencies:
  settings:settings
